# Generated by Django 4.1.4 on 2023-04-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=250)),
                ('phonenumber', models.IntegerField()),
                ('mailid', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('branches', models.CharField(max_length=250)),
                ('accounttype', models.CharField(max_length=250)),
                ('materials', models.CharField(max_length=250)),
            ],
        ),
    ]
